name = "payment-worker"
main = "src/index.ts"
compatibility_date = "2023-02-14"

[[queues.producers]]
  queue = "payment-queue"
  binding = "PAYMENT_QUEUE"

[[queues.consumers]]
 queue = "payment-queue"
 max_batch_size = 1
 max_batch_timeout = 5 # seconds
 max_retries = 3
 dead_letter_queue = "payment-queue-dead"