name = "payment-worker"
main = "src/index.ts"
compatibility_date = "2023-02-14"

[[queues.producers]]
  queue = "payment-listener-queue"
  binding = "PAYMENT_LISTENER_QUEUE"

[[queues.consumers]]
 queue = "payment-listener-queue"
 max_batch_size = 1
 max_batch_timeout = 5 # seconds
 max_retries = 3
 dead_letter_queue = "payment-listener-queue-dead"

[[queues.producers]]
  queue = "payment-write-queue"
  binding = "PAYMENT_WRITE_QUEUE"

[[queues.consumers]]
 queue = "payment-write-queue"
 max_batch_size = 1
 max_batch_timeout = 5 # seconds
 max_retries = 3
 dead_letter_queue = "payment-write-queue-dead"

[[queues.producers]]
  queue = "payment-pusher-queue"
  binding = "PAYMENT_PUSHER_QUEUE"

[[queues.consumers]]
 queue = "payment-pusher-queue"
 max_batch_size = 1
 max_batch_timeout = 5 # seconds
 max_retries = 3
 dead_letter_queue = "payment-pusher-queue-dead"

[[queues.producers]]
  queue = "hook-delivery-queue"
  binding = "HOOK_DELIVERY_QUEUE"

[[queues.consumers]]
 queue = "hook-delivery-queue"
 max_batch_size = 1
 max_batch_timeout = 5 # seconds
 max_retries = 3
 dead_letter_queue = "hook-delivery-queue-dead"

[[queues.producers]]
  queue = "hook-delivery-write-queue"
  binding = "HOOK_DELIVERY_WRITE_QUEUE"

[[queues.consumers]]
 queue = "hook-delivery-write-queue"
 max_batch_size = 1
 max_batch_timeout = 5 # seconds
 max_retries = 3
 dead_letter_queue = "hook-delivery-write-queue-dead"

[[queues.producers]]
  queue = "payment-receiver-queue"
  binding = "PAYMENT_RECEIVER_QUEUE"

[[queues.consumers]]
  queue = "payment-receiver-queue"
  max_batch_size = 1
  max_batch_timeout = 5 # seconds
  max_retries = 0
  dead_letter_queue = "receiver-queue-dead"

[[queues.producers]]
  queue = "payment-sender-queue"
  binding = "PAYMENT_SENDER_QUEUE"

[[queues.consumers]]
  queue = "payment-sender-queue"
  max_batch_size = 1
  max_batch_timeout = 5 # seconds
  max_retries = 0
  dead_letter_queue = "sender-queue-dead"