name = "payment-gateway"
main = "src/index.ts"
compatibility_date = "2024-07-12"

logpush = true

[[queues.producers]]
  queue = "payment-listener-queue"
  binding = "PAYMENT_LISTENER_QUEUE"

[[queues.consumers]]
 queue = "payment-listener-queue"
 max_batch_size = 1
 max_batch_timeout = 5 # seconds
 max_retries = 3
 dead_letter_queue = "payment-listener-queue-dead"

[[queues.producers]]
  queue = "payment-receiver-queue"
  binding = "PAYMENT_RECEIVER_QUEUE"

[[queues.consumers]]
  queue = "payment-receiver-queue"
  max_batch_size = 1
  max_batch_timeout = 5 # seconds
  max_retries = 0
  dead_letter_queue = "receiver-queue-dead"

[[queues.producers]]
  queue = "payment-write-queue"
  binding = "PAYMENT_WRITE_QUEUE"

[[queues.consumers]]
 queue = "payment-write-queue"
 max_batch_size = 1
 max_batch_timeout = 5 # seconds
 max_retries = 3
 dead_letter_queue = "payment-write-queue-dead"

[[queues.producers]]
  queue = "payment-sender-queue"
  binding = "PAYMENT_SENDER_QUEUE"

[[queues.consumers]]
  queue = "payment-sender-queue"
  max_batch_size = 1
  max_batch_timeout = 5 # seconds
  max_retries = 0
  dead_letter_queue = "sender-queue-dead"

[[queues.producers]]
  queue = "webhook-delivery-queue"
  binding = "WEBHOOK_DELIVERY_QUEUE"

[[queues.consumers]]
 queue = "webhook-delivery-queue"
 max_batch_size = 1
 max_batch_timeout = 5 # seconds
 max_retries = 3
 dead_letter_queue = "webhook-delivery-queue-dead"

[[queues.producers]]
  queue = "webhook-delivery-write-queue"
  binding = "WEBHOOK_DELIVERY_WRITE_QUEUE"

[[queues.consumers]]
 queue = "webhook-delivery-write-queue"
 max_batch_size = 1
 max_batch_timeout = 5 # seconds
 max_retries = 3
 dead_letter_queue = "webhook-delivery-write-queue-dead"

[[kv_namespaces]]
  binding = "WALLET"
  preview_id = "ffd2e378dfc14bd99fa3cb56fe4f7508"
  id = "8cad36e3ec214e65bf9ef61f6f6880f1"

[[durable_objects.bindings]]
name = "PAYMENT_LISTENER_DURABLE"
class_name = "PaymentListener"

[[durable_objects.bindings]]
name = "PAYMENT_NOTIFIER"
class_name = "PaymentNotifier"

[[migrations]]
tag = "v1"
new_classes = ["PaymentListenerDurable"]

[[migrations]]
tag = "v2"
renamed_classes = [{from = "PaymentListenerDurable", to = "PaymentListener" }]

[[migrations]]
tag = "v3"
new_classes = ["PaymentNotifier"]
